import type { Metadata } from "next";
import { Geist_Mono, Source_Sans_3 } from "next/font/google";
import "./globals.css";
import "./inspection-tokens.css";
import "./typography.css";
import Providers from "./provider";

const inspectionSans = Source_Sans_3({
  variable: "--font-inspection-sans",
  subsets: ["latin", "thai"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" className={`${inspectionSans.variable} ${geistMono.variable}`}>
      <body> 
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
