import type { Metadata } from "next";
import { Geist_Mono, Noto_Sans_Thai, Source_Sans_3 } from "next/font/google";
import "./globals.css";
import "./inspection-tokens.css";
import "./theme-overrides.css";
import "./typography.css";
import Providers from "./provider";

const inspectionSans = Source_Sans_3({
  variable: "--font-inspection-sans",
  subsets: ["latin", "latin-ext"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const notoThai = Noto_Sans_Thai({
  variable: "--font-noto-thai",
  subsets: ["thai", "latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="th"
      className={`${inspectionSans.variable} ${notoThai.variable} ${geistMono.variable}`}
      data-theme="light"
      suppressHydrationWarning
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem("insp-theme");document.documentElement.dataset.theme=t==="dark"?"dark":"light";}catch(e){}})();`,
          }}
        />
      </head>
      <body suppressHydrationWarning> 
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
